### ISSUE TITLE
Importing '*.csv' into DataFrame errors with: File *.csv does not exist

### ISSUE THREAD

**Issue by ethanwhite** [ContinuumIO/into#85]
A common use of `into` would be to import/convert all of the csv files in a directory. This works fine if there is a prefix to the asterix, e.g.,
`into(pd.DataFrame, 'examp*.csv')`

but errors if there is no prefix,
```
>>> into(pd.DataFrame, '*.csv')
...
IOError: File *.csv does not exist
```

**Comment by cpcloud** [comment]
You should be able to do

into(pd.DataFrame, "./*.csv")

We could probably implement this fairly quickly.

**Comment by ethanwhite** [comment]
That actually doesn't work for me either:
```
>>> into(pd.DataFrame, './*.csv')
...
KeyError: <class 'into.directory.Directory(CSV)'>
```

Regardless, I think that the `'*.csv'` use will be common enough that it's worth implementing.

Thanks for building a really cool tool! My research group will definitely be making good use of it.

**Comment by cpcloud** [comment]
Glad you like it! @mrocklin is the mastermind behind the project. I agree it's a sorely needed technology in a world where data formats multiply like rabbits and CSV is ubiquitous.

**Comment by mrocklin** [comment]
Should be fixed in https://github.com/ContinuumIO/into/pull/86 .  It was a silly problem with our regexes and a simple fix.  Thank you very much for reporting @ethanwhite .

**Comment by ethanwhite** [comment]
Awesome! Thanks for the quick fix. Always happy to report issues. It's how we get the best software.

**Comment by mohamedahmedawad93** [comment]
I still have this issue
my code is 
```
>>> import pandas as pd
>>> from odo import into
>>> into(pd.DataFrame, './*.csv')
```
and this is the full traceback error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/odo/into.py", line 43, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/odo/into.py", line 149, in into_string_string
    return into(a, resource(b, **kwargs), **kwargs)
  File "/usr/local/lib/python2.7/site-packages/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/odo/into.py", line 43, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/odo/into.py", line 53, in into_type
    return convert(a, b, dshape=dshape, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/odo/core.py", line 44, in __call__
    return _transform(self.graph, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/odo/core.py", line 57, in _transform
    ooc_types=ooc_types)
  File "/usr/local/lib/python2.7/site-packages/odo/core.py", line 92, in path
    pth = nx.shortest_path(g, source=source, target=target, weight='cost')
  File "/usr/local/lib/python2.7/site-packages/networkx/algorithms/shortest_paths/generic.py", line 138, in shortest_path
    paths=nx.dijkstra_path(G,source,target,weight)
  File "/usr/local/lib/python2.7/site-packages/networkx/algorithms/shortest_paths/weighted.py", line 78, in dijkstra_path
    weight=weight)
  File "/usr/local/lib/python2.7/site-packages/networkx/algorithms/shortest_paths/weighted.py", line 296, in single_source_dijkstra
    target=target)
  File "/usr/local/lib/python2.7/site-packages/networkx/algorithms/shortest_paths/weighted.py", line 356, in _dijkstra
    for u, e in G_succ[v].items():
KeyError: <class 'odo.directory._Directory'>
```
I have also tried 
```
>>> into(pd.DataFrame, '*.csv')
```
and I got instead
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/odo/into.py", line 43, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/odo/into.py", line 149, in into_string_string
    return into(a, resource(b, **kwargs), **kwargs)
  File "/usr/local/lib/python2.7/site-packages/odo/regex.py", line 91, in __call__
    return self.dispatch(s)(s, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/odo/backends/csv.py", line 364, in resource_glob
    r = resource(filenames[0], **kwargs)
IndexError: list index out of range
```
Any suggestions?
